cask "spotify"
cask "whatsapp"
cask "corretto@11"
cask "oracle-jdk@21"
cask "iterm2"

brew "clojure"
brew "coursier"
brew "wget"
brew "fzf"
brew "telnet"
brew "go"
brew "git"
brew "docker-compose"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"
